# Generated by Django 3.2.8 on 2022-05-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220530_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_customer',
            new_name='is_organization',
        ),
        migrations.AddField(
            model_name='account',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
