# Generated by Django 3.2.8 on 2022-05-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220530_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Organization', 'Organization'), ('Student', 'Student')], default='Student', max_length=25),
        ),
    ]
