# Generated by Django 3.2.8 on 2022-06-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Attachment',
            new_name='attachment',
        ),
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.CharField(default='', max_length=244),
            preserve_default=False,
        ),
    ]
