# Generated by Django 3.2.8 on 2022-06-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20220622_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(default='test.pdf', upload_to=''),
        ),
    ]
