# Generated by Django 3.2.8 on 2022-06-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='attachment',
            new_name='Attachment',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cv',
        ),
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
