# Generated by Django 3.2.8 on 2022-06-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20220622_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Attachment',
            new_name='attachment',
        ),
    ]
