# Generated by Django 3.2.8 on 2022-06-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_rename_attachment_application_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
