# Generated by Django 3.2.8 on 2022-06-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=1, max_length=25),
        ),
    ]
